
disabled_rules: # rule identifiers to exclude from running
- force_cast
- for_where
- notification_center_detachment
- trailing_whitespace
- identifier_name
- void_return
- unused_optional_binding


opt_in_rules:
- empty_count
- empty_string

#Customized Rules
line_length:
    warning: 250
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true


file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
    
type_body_length:
    warning: 300
    error: 500
    
function_body_length:
    warning: 300
    error: 500
    
function_parameter_count:
    warning: 6
    error: 8
    
cyclomatic_complexity:
    warning: 15
    error: 25
    
vertical_whitespace:
    warning: 3
    max_empty_lines: 2
    

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- Carthage
- SwiftLint/Common/3rdPartyLib

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)

